name: Check Stock

on:
  schedule:
    # Mỗi 10 phút kiểm tra
    - cron: "*/10 * * * *"
    # 12h trưa VN (UTC+7 = 05:00 UTC)
    - cron: "0 5 * * *"
    # 12h đêm VN (UTC+7 = 17:00 UTC)
    - cron: "0 17 * * *"
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run check script
        run: python check_and_notify.py
