name: Stock Checker

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"       # 10 phút/lần check
    - cron: "0 5,17 * * *"       # 12h trưa & 0h đêm (giờ VN = UTC+7 → UTC-7h)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 pytz
      - name: Run script
        run: python check_and_notify.py
